"""add column for currency

Revision ID: 54984f944968
Revises: 8b81d3a4ec26
Create Date: 2025-04-18 00:38:52.570443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54984f944968'
down_revision: Union[str, None] = '8b81d3a4ec26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websites', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websites', 'currency')
    # ### end Alembic commands ###
