services:
  technesis:
    env_file: .env
    build: .
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./pgdata:/var/lib/postgresql/data
    command: sh -c "alembic upgrade head && python3 run.py"
  technesisdb:
    image: postgres:15
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/lib/technesis/postgres_data:/var/lib/postgresql/data
    ports:
      - "5437:5437"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      
